define(['angular'], function (angular) {
    'use strict';

    angular.module('ContentFixture', [])
        .service('ContentFixture', [ function () {


            return {"UNIT1": [
                {
                    "vocitem": "relative",
                    "vocdef": "a member of your family",
                    "vocsound": "sound/relative.mp3",
                    "vocimg": "images/content/relative.jpg",
                    "distractor1": "roots",
                    "dis1def": "your relation to a place because you were born there, or your family used to live there",
                    "dis1sound": "sound/roots.mp3",
                    "dis1img": "images/content/roots.jpg",
                    "distractor2": "grandparent",
                    "dis2def": "parent of your mother or father",
                    "dis2sound": "sound/grandparent.mp3",
                    "dis2img": "images/content/grandmother.jpg",
                    "distractor3": "ancestor",
                    "dis3def": "a member of your family who lived a long time ago",
                    "dis3sound": "sound/ancestor.mp3",
                    "dis3img": "images/content/ancestor.jpg",
                    "sentence1": "Mammoth looked like its modern ",
                    "sentence2": "- the elephant."
                },
                {
                    "vocitem": "ancestor",
                    "vocdef": "a member of your family who lived a long time ago",
                    "vocsound": "sound/ancestor.mp3",
                    "vocimg": "images/content/ancestor.jpg",
                    "distractor1": "friend",
                    "dis1def": "someone who you know and like very much and enjoy spending time with",
                    "dis1sound": "sound/friend.mp3",
                    "dis1img": "images/content/friend.jpg",
                    "distractor2": "brother",
                    "dis2def": "a male who has the same parents as you",
                    "dis2sound": "sound/brother.mp3",
                    "dis2img": "images/content/brother.jpg",
                    "distractor3": "son",
                    "dis3def": "someone's male child",
                    "dis3sound": "sound/son.mp3",
                    "dis3img": "images/content/son.jpg",
                    "sentence1": "Researchers agree that our ",
                    "sentence2": ", the upright walking ape, lived in Africa."
                },
                {
                    "vocitem": "anniversary",
                    "vocdef": "a date on which something special or important happened in a previous year",
                    "vocsound": "sound/anniversary.mp3",
                    "vocimg": "images/content/anniversary.jpg",
                    "distractor1": "birthplace",
                    "dis1def": "the place where someone was born, used especially when talking about someone famous",
                    "dis1sound": "sound/birthplace.mp3",
                    "dis1img": "images/content/birthplace.jpg",
                    "distractor2": "project",
                    "dis2def": "a carefully planned piece of work to get information about something, to build something or to improve something",
                    "dis2sound": "sound/project.mp3",
                    "dis2img": "images/content/project.jpg",
                    "distractor3": "insurance",
                    "dis3def": "an arrangement with a company in which you pay them money, especially regularly, and they pay the costs if you become ill or your car is damaged",
                    "dis3sound": "sound/insurance.mp3",
                    "dis3img": "images/content/insurance.jpg",
                    "sentence1": "The couple will celebrate their ten year ",
                    "sentence2": " this May 3rd."
                },
                {
                    "vocitem": "extended family",
                    "vocdef": "a family group that consists not only of parents and children but also of grandparents",
                    "vocsound": "sound/extended_family.mp3",
                    "vocimg": "images/content/extended_family.jpg",
                    "distractor1": "marriage",
                    "dis1def": "the relationship between two people who are married",
                    "dis1sound": "sound/marriage.mp3",
                    "dis1img": "images/content/marriage.jpg",
                    "distractor2": "boss",
                    "dis2def": "the person who employs you or who is in charge of you at work",
                    "dis2sound": "sound/boss.mp3",
                    "dis2img": "images/content/boss.jpg",
                    "distractor3": "classmate",
                    "dis3def": "a member of the same class in a school, college or, in the US, a university",
                    "dis3sound": "sound/classmate.mp3",
                    "dis3img": "images/content/classmate.jpg",
                    "sentence1": "Once a month we meet with our ",
                    "sentence2": " on family dinner."
                },
                {
                    "vocitem": "roots",
                    "vocdef": "your relation to a place because you were born there, or your family used to live there",
                    "vocsound": "sound/roots.mp3",
                    "vocimg": "images/content/roots.jpg",
                    "distractor1": "ancestor",
                    "dis1def": "a member of your family who lived a long time ago",
                    "dis1sound": "sound/ancestor.mp3",
                    "dis1img": "images/content/ancestor.jpg",
                    "distractor2": "parents",
                    "dis2def": "mother and father of a person or animal",
                    "dis2sound": "sound/parents.mp3",
                    "dis2img": "images/content/parents.jpg",
                    "distractor3": "employee",
                    "dis3def": "someone who is paid to work for someone else",
                    "dis3sound": "sound/employee.mp3",
                    "dis3img": "images/content/employee.jpg",
                    "sentence1": "Jenn has Polish ",
                    "sentence2": ". Her grandfather was from Warsaw."
                },
                {
                    "vocitem": "team-mate",
                    "vocdef": "someone who belongs to the same team as you",
                    "vocsound": "sound/teammate.mp3",
                    "vocimg": "images/content/teammate.jpg",
                    "distractor1": "relative",
                    "dis1def": "a member of your family",
                    "dis1sound": "sound/relative.mp3",
                    "dis1img": "images/content/relative.jpg",
                    "distractor2": "godfather",
                    "dis2def": "male who promises at a baptism ceremony to help a child, and to teach him or her Christian values",
                    "dis2sound": "sound/godfather.mp3",
                    "dis2img": "images/content/godfather.jpg",
                    "distractor3": "fiancée",
                    "dis3def": "the woman whom a man is going to marry",
                    "dis3sound": "sound/fiancee.mp3",
                    "dis3img": "images/content/fiancee.jpg",
                    "sentence1": "He finished just ahead of his Ferrari ",
                    "sentence2": "."
                },
                {
                    "vocitem": "employee",
                    "vocdef": "someone who is paid to work for someone else",
                    "vocsound": "sound/employee.mp3",
                    "vocimg": "images/content/employee.jpg",
                    "distractor1": "extended family",
                    "dis1def": "a family group that consists not only of parents and children but also of grandparents",
                    "dis1sound": "sound/extended_family.mp3",
                    "dis1img": "images/content/extended_family.jpg",
                    "distractor2": "cousin",
                    "dis2def": "the child of your uncle or aunt",
                    "dis2sound": "sound/cousin.mp3",
                    "dis2img": "images/content/cousin.jpg",
                    "distractor3": "team-mate",
                    "dis3def": "someone who belongs to the same team as you",
                    "dis3sound": "sound/teammate.mp3",
                    "dis3img": "images/content/teammate.jpg",
                    "sentence1": "As a company’s ",
                    "sentence2": " he was entitled to all benefits."
                },
                {
                    "vocitem": "godmother",
                    "vocdef": "female who promises at a baptism ceremony to help a child, and to teach him or her Christian values",
                    "vocsound": "sound/godmother.mp3",
                    "vocimg": "images/content/godmother.jpg",
                    "distractor1": "pupil",
                    "dis1def": "someone who is being taught, especially a child",
                    "dis1sound": "sound/pupil.mp3",
                    "dis1img": "images/content/pupil.jpg",
                    "distractor2": "great grandparent",
                    "dis2def": "a parent of your grandparent",
                    "dis2sound": "sound/great_grandparent.mp3",
                    "dis2img": "images/content/great_grandparent.jpg",
                    "distractor3": "grandmother",
                    "dis3def": "the mother of your mother or father",
                    "dis3sound": "sound/grandmother.mp3",
                    "dis3img": "images/content/grandmother.jpg",
                    "sentence1": "I became ",
                    "sentence2": " to my sister’s daughter."
                },
                {
                    "vocitem": "fiancée",
                    "vocdef": "the woman whom a man is going to marry",
                    "vocsound": "sound/fiancee.mp3",
                    "vocimg": "images/content/fiancee.jpg",
                    "distractor1": "wife",
                    "dis1def": "the woman that a man is married to",
                    "dis1sound": "sound/wife.mp3",
                    "dis1img": "images/content/wife.jpg",
                    "distractor2": "brother",
                    "dis2def": "a male who has the same parents as you",
                    "dis2sound": "sound/brother.mp3",
                    "dis2img": "images/content/brother.jpg",
                    "distractor3": "husband",
                    "dis3def": "the man that a woman is married to",
                    "dis3sound": "sound/husband.mp3",
                    "dis3img": "images/content/husband.jpg",
                    "sentence1": "My ",
                    "sentence2": " and I will be married on June."
                },
                {
                    "vocitem": "member",
                    "vocdef": "a person that belongs to a group",
                    "vocsound": "sound/member.mp3",
                    "vocimg": "images/content/member.jpg",
                    "distractor1": "pupil",
                    "dis1def": "someone who is being taught, especially a child",
                    "dis1sound": "sound/pupil.mp3",
                    "dis1img": "images/content/pupil.jpg",
                    "distractor2": "classmate",
                    "dis2def": "a member of the same class in a school, college or, in the US, a university",
                    "dis2sound": "sound/classmate.mp3",
                    "dis2img": "images/content/classmate.jpg",
                    "distractor3": "student",
                    "dis3def": "someone who is studying at a university, school etc",
                    "dis3sound": "sound/student.mp3",
                    "dis3img": "images/content/student.jpg",
                    "sentence1": "The newest ",
                    "sentence2": " of their team, Jake, wasn't quite comfortable yet."
                }
            ] };

        }]);
});